""" Migration #6 after adding confirmed column

Revision ID: 12b17c8fae8a
Revises: e0a8264173b
Create Date: 2014-04-05 10:50:07.775782

"""

# revision identifiers, used by Alembic.
revision = '12b17c8fae8a'
down_revision = 'e0a8264173b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monkeys', 'confirmed')
    ### end Alembic commands ###
