"""BestFriend added column

Revision ID: 1a3938723bf
Revises: 315a7ab9a029
Create Date: 2014-04-15 14:16:51.832992

"""

# revision identifiers, used by Alembic.
revision = '1a3938723bf'
down_revision = '315a7ab9a029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_friends', sa.Column('best_friend_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('best_friends', 'best_friend_id')
    ### end Alembic commands ###
