"""Migration #3

Revision ID: 1f3db8a47a01
Revises: 38aa704acc80
Create Date: 2014-04-03 22:02:01.291174

"""

# revision identifiers, used by Alembic.
revision = '1f3db8a47a01'
down_revision = '38aa704acc80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
