"""BestFriend improved

Revision ID: 220b97891094
Revises: 3b90540a54d
Create Date: 2014-04-15 17:22:51.797226

"""

# revision identifiers, used by Alembic.
revision = '220b97891094'
down_revision = '3b90540a54d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
