"""Models improved

Revision ID: 2627e783bdcf
Revises: 2e0ca81f0689
Create Date: 2014-04-22 12:49:51.602226

"""

# revision identifiers, used by Alembic.
revision = '2627e783bdcf'
down_revision = '2e0ca81f0689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('best_friends', 'best_friend_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('best_friends', 'best_friend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
