"""Follow model improved

Revision ID: 2e0ca81f0689
Revises: 220b97891094
Create Date: 2014-04-15 23:40:31.041158

"""

# revision identifiers, used by Alembic.
revision = '2e0ca81f0689'
down_revision = '220b97891094'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
