"""BestFriend model changed

Revision ID: 315a7ab9a029
Revises: 8ce0330bbc2
Create Date: 2014-04-15 13:21:16.720397

"""

# revision identifiers, used by Alembic.
revision = '315a7ab9a029'
down_revision = '8ce0330bbc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'best_friends', ['friend_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'best_friends')
    ### end Alembic commands ###
