"""BestFriend improved

Revision ID: 34513002ed33
Revises: 1a3938723bf
Create Date: 2014-04-15 14:54:09.700635

"""

# revision identifiers, used by Alembic.
revision = '34513002ed33'
down_revision = '1a3938723bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
