"""Migration #2

Revision ID: 38aa704acc80
Revises: 433ba5df7f6f
Create Date: 2014-04-01 16:12:34.275568

"""

# revision identifiers, used by Alembic.
revision = '38aa704acc80'
down_revision = '433ba5df7f6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_friends',
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkeys.id'], ),
    sa.UniqueConstraint('monkey_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('best_friends')
    ### end Alembic commands ###
