""" Migration #7 added avatar column

Revision ID: 3a49ceeeceb
Revises: 12b17c8fae8a
Create Date: 2014-04-06 12:26:43.578882

"""

# revision identifiers, used by Alembic.
revision = '3a49ceeeceb'
down_revision = '12b17c8fae8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monkeys', 'avatar_hash')
    ### end Alembic commands ###
