"""BestFriend improved

Revision ID: 3b90540a54d
Revises: 34513002ed33
Create Date: 2014-04-15 14:56:12.016025

"""

# revision identifiers, used by Alembic.
revision = '3b90540a54d'
down_revision = '34513002ed33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
