""" Migration #8 improved constructor

Revision ID: 3c0783aa9966
Revises: 3a49ceeeceb
Create Date: 2014-04-06 12:32:16.414660

"""

# revision identifiers, used by Alembic.
revision = '3c0783aa9966'
down_revision = '3a49ceeeceb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
