"""Migration #1

Revision ID: 433ba5df7f6f
Revises: None
Create Date: 2014-04-01 14:52:54.429622

"""

# revision identifiers, used by Alembic.
revision = '433ba5df7f6f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('monkey_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkeys.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    ### end Alembic commands ###
