""" Migration #14 Removed FK with best_friend_id

Revision ID: 4e320af1f5f8
Revises: 6116bf12913
Create Date: 2014-04-11 08:42:36.057635

"""

# revision identifiers, used by Alembic.
revision = '4e320af1f5f8'
down_revision = '6116bf12913'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('best_friends', 'best_friend_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_friends', sa.Column('best_friend_id', mysql.INTEGER(display_width=11), nullable=False))
    ### end Alembic commands ###
