""" Migration #10 timestamp column added

Revision ID: 4fc4c5fc53e0
Revises: 4ef8d58a83a1
Create Date: 2014-04-08 23:09:21.305989

"""

# revision identifiers, used by Alembic.
revision = '4fc4c5fc53e0'
down_revision = '4ef8d58a83a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'timestamp')
    ### end Alembic commands ###
