"""Migration #4

Revision ID: 569ce62dbcdc
Revises: 1f3db8a47a01
Create Date: 2014-04-03 22:32:12.959930

"""

# revision identifiers, used by Alembic.
revision = '569ce62dbcdc'
down_revision = '1f3db8a47a01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
