""" Migration #13 Added FK with best friend name

Revision ID: 6116bf12913
Revises: 34fb23b9bce4
Create Date: 2014-04-11 00:40:58.863198

"""

# revision identifiers, used by Alembic.
revision = '6116bf12913'
down_revision = '34fb23b9bce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
