"""Models improved

Revision ID: 684f9e3b518
Revises: 2627e783bdcf
Create Date: 2014-04-22 14:39:17.072709

"""

# revision identifiers, used by Alembic.
revision = '684f9e3b518'
down_revision = '2627e783bdcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
