"""Initial migration for Heroku

Revision ID: 8ce0330bbc2
Revises: None
Create Date: 2014-04-12 09:15:22.524186

"""

# revision identifiers, used by Alembic.
revision = '8ce0330bbc2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monkeyname', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monkeys_email', 'monkeys', ['email'], unique=True)
    op.create_index('ix_monkeys_monkeyname', 'monkeys', ['monkeyname'], unique=True)
    op.create_table('best_friends',
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('best_friend_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['best_friend_name'], ['monkeys.monkeyname'], ),
    sa.ForeignKeyConstraint(['friend_id'], ['monkeys.id'], ),
    sa.PrimaryKeyConstraint('friend_id'),
    sa.UniqueConstraint('friend_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['monkeys.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['monkeys.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('best_friends')
    op.drop_index('ix_monkeys_monkeyname', table_name='monkeys')
    op.drop_index('ix_monkeys_email', table_name='monkeys')
    op.drop_table('monkeys')
    ### end Alembic commands ###
