""" Migration #11 BestFriend class added

Revision ID: c9adfcdaae6
Revises: 4fc4c5fc53e0
Create Date: 2014-04-09 13:19:42.476439

"""

# revision identifiers, used by Alembic.
revision = 'c9adfcdaae6'
down_revision = '4fc4c5fc53e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('best_friends', sa.Column('best_friend_id', sa.Integer(), nullable=False))
    #op.drop_column('best_friends', 'monkey_id')
    op.alter_column('best_friends', 'friend_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    #op.drop_constraint(u'monkey_id', 'best_friends', 'unique')  # edited manually, added type 'unique'
    op.create_unique_constraint(None, 'best_friends', ['friend_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'best_friends')
    op.create_unique_constraint(u'monkey_id', 'best_friends', ['monkey_id'])
    op.alter_column('best_friends', 'friend_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('best_friends', sa.Column('monkey_id', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('best_friends', 'best_friend_id')
    ### end Alembic commands ###
