"""Migration #5

Revision ID: e0a8264173b
Revises: 569ce62dbcdc
Create Date: 2014-04-04 17:39:08.155239

"""

# revision identifiers, used by Alembic.
revision = 'e0a8264173b'
down_revision = '569ce62dbcdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
